# Generated by Django 3.1.7 on 2021-03-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name/Description')),
                ('heritageId', models.CharField(blank=True, help_text='Useful to cross-reference with other systems', max_length=200, null=True, unique=True, verbose_name='Alternative ID')),
                ('url', models.URLField(blank=True, help_text='A page on your website that is relevant to this item', max_length=255, null=True, verbose_name='URL')),
                ('location', models.CharField(blank=True, help_text='Where is your item located on the premises', max_length=200, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('isActive', models.BooleanField(default=True, help_text='Is this item available for playback on the devices?', verbose_name='Active?')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name/Description')),
                ('nfcTag', models.CharField(blank=True, max_length=50, null=True, verbose_name='NFC Tag')),
                ('tts', models.BooleanField(default=True, help_text='Do you the system automatically generate an audio file from the text you provide?', verbose_name='Use TTS')),
                ('text', models.TextField(blank=True, help_text='Text to convert into an audio file', null=True, verbose_name='Text to convert to speech')),
                ('soundFile', models.FileField(blank=True, help_text='Audio file for use instead of text to be converted to sound', null=True, upload_to='')),
                ('gesture', models.CharField(choices=[('NON', 'none'), ('SHK', 'shake'), ('TLT', 'tilt'), ('TRN', 'turn over/upside down')], default='NON', help_text='If set, the gesture will be prompted for after the audio has played', max_length=25)),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritage.item')),
            ],
        ),
    ]
