# Generated by Django 3.1.7 on 2021-03-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='tts',
            new_name='useTts',
        ),
    ]
