# Generated by Django 3.1.7 on 2021-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0002_auto_20210318_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
        migrations.AddField(
            model_name='item',
            name='website',
            field=models.URLField(blank=True, help_text='A page on your website that is relevant to this item', max_length=255, null=True, verbose_name='Website'),
        ),
    ]
