# Generated by Django 3.1.7 on 2021-03-18 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0003_auto_20210318_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_content', to='heritage.item'),
        ),
    ]
