# Generated by Django 3.1.7 on 2021-03-18 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0004_auto_20210318_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='soundFile',
            field=models.FileField(blank=True, help_text='Audio file for use instead of text to be converted to sound', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
