# Generated by Django 3.1.7 on 2021-03-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0005_auto_20210318_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkName', models.CharField(max_length=40, unique=True, verbose_name='Network Name/IP Address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Any notes about this particular device')),
            ],
        ),
    ]
