# -*- makefile -*-
#
# This file is automatically generated by configure.
# Do not hand edit.

OSTYPE		:= linux-gnueabihf
MACHINETYPE	:= armv6l
PLATFORM	:= armv6l-unknown-linux-gnueabihf
FULLOSTYPE	:= unknown-linux-gnueabihf
